### ISSUE TITLE
./tools/bin_vocabulary doesn't exist

### ISSUE THREAD

**Issue by rrustagi20** [ivalab/gf_orb_slam2#2]
title

**Comment by shiyuF** [comment]
@rrustagi20  Use the readme in the correct branch.

**Comment by rrustagi20** [comment]
@shiyuF file not present either in `feature/ubuntu20.04` branch or `noetic/catkin_traj_servo` branch

**Comment by shiyuF** [comment]
@rrustagi20 As mentioned in a previous comment.
